export const FETCH_USER = 'FETCH_USER'
export const SEARCH_TRAILS = 'SEARCH_TRAILS'
export const TOGGLE_WISHLIST = 'TOGGLE_WISHLIST'
export const TOGGLE_COMPLETE = 'TOGGLE_COMPLETE'
export const SORT_TRAILS = 'SORT_TRAILS'
export const FETCH_TRAIL = 'FETCH_TRAIL'
export const OPEN_MODAL = 'OPEN_MODAL'
export const REFRESH_MAP = 'REFRESH_MAP'
export const INFO_WINDOW = 'INFO_WINDOW'
export const EXTENDED_INFO = 'EXTENDED_INFO'
export const SCREEN_RESIZE = 'SCREEN_RESIZE'


